### ISSUE TITLE
Interpolation NN

### ISSUE THREAD

**Issue by ainglot** [facebookresearch/pysparnn#9]
Hello,
I have spatial data (points in Cartesian x, y, z.). I need to designate new value “z” using algorithm Natural Neighbour. Should I use PySparNN or different library? I ask because I haven’t been able to install annoy in win7.

**Comment by spencebeecher** [comment]
Great question! While you definitely can use pysparnn - I would recommend that you use one of the methods in scikit-learn. http://scikit-learn.org/stable/modules/classes.html#module-sklearn.neighbors

KD-Tree or Ball Tree should do very well for you. Those should be easy to install. Annoy is another great project that may also work for you - https://github.com/spotify/annoy .

PySparNN works very well in large dimensions where the number of positive entries per record is small. Like a text doccument - there are many possible words (dimensions) but where the number of positive entries per record is small (0,0,0,0,0,0,0,0,10,0,0,0,0,0,0,0,0,0,1,1).
